"""add published_year to books

Revision ID: 2142746b38cf
Revises: 554c4f813cb4
Create Date: 2026-08-28 09:45:21.113000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2142746b38cf'
down_revision: Union[str, Sequence[str], None] = '554c4f813cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###
